str() takes at most 1 argument (2 given)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 43, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/landing_page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/base.html", line 159, in top-level template code
    {{ forms['advanced'][_form_names.name_province](
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/widgets/core.py", line 288, in __call__
    html.append(self.render_option(val, label, selected))
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/hack.py", line 141, in render_option
    func_result = str(value, 'utf-8') if isinstance(value, string_types) else coerce_func(value)
TypeError: str() takes at most 1 argument (2 given)
name 'unicode' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 118, in view_results
    filter_form=_filter_form)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 672, in inject_updated_locale_urls
    _args.append((unicode(arg).encode('utf-8'), unicode(arg_v).encode('utf-8')))
NameError: name 'unicode' is not defined
module 'urllib' has no attribute 'urlencode'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 118, in view_results
    filter_form=_filter_form)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 673, in inject_updated_locale_urls
    _request_url = urllib.urlencode(_args)
AttributeError: module 'urllib' has no attribute 'urlencode'
'ascii' codec can't encode characters in position 27-28: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 118, in view_results
    filter_form=_filter_form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 672, in inject_updated_locale_urls
    _args.append((str(arg).encode('utf-8'), str(arg_v).encode('utf-8')))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 27-28: ordinal not in range(128)
sequence item 1: expected str instance, bytes found
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 118, in view_results
    filter_form=_filter_form)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 659, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 27, in get_portal_data
    providers = self.get_partner_stats()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 54, in get_partner_stats
    if provider.logo is not None:
  File "/usr/lib/python3.7/site-packages/sqlalchemy/ext/hybrid.py", line 744, in __get__
    return self.fget(instance)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/models.py", line 35, in logo
    return multimedia_to_image(multimedia)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/helper.py", line 37, in multimedia_to_image
    _encoded_multimedia_type])
TypeError: sequence item 1: expected str instance, bytes found
